### ISSUE TITLE
PHP ERROR

### ISSUE THREAD

**Issue by jrosetto** [AlexEdimensionz/Todoyu-PHP7.x#2]
Thank you for picking up on this project.  We use it as a ticketing system as an MSP provider and rely on it pretty heavily.

I moved from a Debian 8 over to a Ubuntu 18.10 install migrating the files and mysql databases which was originally on the official 2.3.1 from sourceforge.  Everything seems to be working fine except clicking from the 'Portal' tab between 'MY FILTERS', 'TO DO's', 'FEEDBACK', and 'EVENTS'.

Here is the error in the log when transitioning.

e2268822cd :: 2019-05-30 12:08:17 - L:3 - U:jrosetto [core/model/TodoyuAutoloader.class.php:56] :: PHP ERROR: [2] Declaration of TodoyuCalendarEventAssignment::getPerson() should be compatible with TodoyuBaseObject::getPerson($type)
e2268822cd :: 2019-05-30 12:08:17 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderPopup.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderPopup::getDateRemind() should be compatible with TodoyuCalendarReminder::getDateRemind($reminderType = CALENDAR_TYPE_EVENTREMINDER_EMAIL)
e2268822cd :: 2019-05-30 12:08:17 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderPopup.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderPopup::getAdvanceTime() should be compatible with TodoyuCalendarReminder::getAdvanceTime($type = CALENDAR_TYPE_EVENTREMINDER_EMAIL)
e2268822cd :: 2019-05-30 12:08:17 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderPopup.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderPopup::isDisabled() should be compatible with TodoyuCalendarReminder::isDisabled($reminderType)
10c5e14f12 :: 2019-05-30 12:08:17 - L:3 - U:jrosetto [core/model/TodoyuAutoloader.class.php:56] :: PHP ERROR: [2] Declaration of TodoyuCalendarEventAssignment::getPerson() should be compatible with TodoyuBaseObject::getPerson($type)
10c5e14f12 :: 2019-05-30 12:08:17 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderPopup.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderPopup::getDateRemind() should be compatible with TodoyuCalendarReminder::getDateRemind($reminderType = CALENDAR_TYPE_EVENTREMINDER_EMAIL)
10c5e14f12 :: 2019-05-30 12:08:17 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderPopup.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderPopup::getAdvanceTime() should be compatible with TodoyuCalendarReminder::getAdvanceTime($type = CALENDAR_TYPE_EVENTREMINDER_EMAIL)
10c5e14f12 :: 2019-05-30 12:08:17 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderPopup.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderPopup::isDisabled() should be compatible with TodoyuCalendarReminder::isDisabled($reminderType)

Any suggestions would be greatly appreciated,

Thanks.

**Comment by AlexEdimensionz** [comment]
Hi @jrosetto,
I pushed a change that should fix the PHP warnings.  Please let me know if you are still experiencing bugs. 

If you still have bugs, can you send me AJAX response data from the click to see if maybe there is something else wrong.

**Comment by AlexEdimensionz** [comment]
The changes are in the repo, not in the Release zip file

**Comment by jrosetto** [comment]
Now just getting a blank page.  I also tried removing everything in the cache folder to make sure it had nothing to do with that.

Current error from todoyu

bc2e436f27 :: 2019-05-30 14:57:19 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderPopup.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderPopup::isDisabled() should be compatible with TodoyuCalendarReminder::isDisabled($reminderType)

Apache Error Log

[Thu May 30 18:59:05.105756 2019] [php7:error] [pid 1242] [client 192.168.5.197:60807] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function TodoyuCalendarReminderPopup::isDismissed(), 0 passed in /var/www/html/ext/calendar/model/TodoyuCalendarReminderPopupManager.class.php on line 200 and exactly 1 expected in /var/www/html/ext/calendar/model/TodoyuCalendarReminderPopup.class.php:56\nStack trace:\n#0 /var/www/html/ext/calendar/model/TodoyuCalendarReminderPopupManager.class.php(200): TodoyuCalendarReminderPopup->isDismissed()\n#1 /var/www/html/ext/calendar/model/TodoyuCalendarReminderPopupManager.class.php(173): TodoyuCalendarReminderPopupManager::getUpcomingReminderEvents()\n#2 /var/www/html/ext/calendar/config/page.php(40): TodoyuCalendarReminderPopupManager::addReminderJsInitToPage()\n#3 /var/www/html/core/model/TodoyuFileManager.class.php(1156): include_once('/var/www/html/e...')\n#4 /var/www/html/core/model/TodoyuExtensions.class.php(223): TodoyuFileManager::includeFile('/var/www/html/e...', true, true)\n#5 /var/www/html/core/model/TodoyuExtensions.class.php(308): TodoyuExtensions::loadConfi in /var/www/html/ext/calendar/model/TodoyuCalendarReminderPopup.class.php on line 56, referer: http://192.168.5.61/

I've taken it out of production and rolled back to 2.3.1 so business can still function.  I have the PHP7 spun up on a VM to test until things are stable.

Thanks again for the assistance.  Happy to see new life in TodoYU.

**Comment by AlexEdimensionz** [comment]
I will get this fixed asap

**Comment by jrosetto** [comment]
No hurry, just excited to get everything running on current packages :-)

**Comment by AlexEdimensionz** [comment]
I have fixed these issues as well. we never noticed them before because they are supposed to be notices. Somehow in your PHP config you have notices firing as Errors. 

If you pull the latest and give it another shot. that vector causing errors should stop

**Comment by melissa-edimensionz** [comment]
Awesome!
I'm back. Can he pull the repo or should I tell him will be available soon

**Comment by jrosetto** [comment]
Getting closer but still having issues with the calendar when adding events.  The toggle works now on the portal page. 

941af4a8e1 :: 2019-06-03 17:03:31 - L:3 - U: [/var/www/html:0] :: PHP ERROR: [2] sizeof(): Parameter must be an array or an object that implements Countable
941af4a8e1 :: 2019-06-03 17:03:32 - L:3 - U: [/var/www/html:0] :: PHP ERROR: [2] sizeof(): Parameter must be an array or an object that implements Countable
4498a06de9 :: 2019-06-03 17:03:40 - L:2 - U: [core/model/TodoyuAuth.class.php:111] :: Login person (2)
2f52b5429f :: 2019-06-03 17:03:43 - L:3 - U:jrosetto [/var/www/html:0] :: PHP ERROR: [2] sizeof(): Parameter must be an array or an object that implements Countable
2f52b5429f :: 2019-06-03 17:03:43 - L:3 - U:jrosetto [/var/www/html:0] :: PHP ERROR: [2] sizeof(): Parameter must be an array or an object that implements Countable
1100cfac74 :: 2019-06-03 17:03:45 - L:3 - U:jrosetto [core/model/TodoyuAutoloader.class.php:56] :: PHP ERROR: [2] Declaration of TodoyuCalendarEventActionController::init($params) should be compatible with TodoyuActionController::init(array $params = Array)

Sorry for the delay, was off Friday and had fires to put out this morning.

**Comment by AlexEdimensionz** [comment]
You are getting this error after login?

**Comment by jrosetto** [comment]
I'm getting the error when creating a new Event on the calendar.

**Comment by AlexEdimensionz** [comment]
I pushed another batch of changes that should hopefully fix your issues.
I can't recreate the sideof() error

**Comment by AlexEdimensionz** [comment]
The sizeof() error is fixed in the latest push as well. If any more errors popup, please let me know

**Comment by AlexEdimensionz** [comment]
If this all works out, do you mind creating an Issue for a feature request. Something that you feel is missing from Todoyu for your company's workflow.

Thank you

**Comment by jrosetto** [comment]
Everything looks good on the fontend now.

I am still getting the error

7ccd1d6760 :: 2019-06-03 18:40:19 - L:3 - U:jrosetto [/var/www/html:0] :: PHP ERROR: [2] sizeof(): Parameter must be an array or an object that implements Countable
7ccd1d6760 :: 2019-06-03 18:40:19 - L:3 - U:jrosetto [/var/www/html:0] :: PHP ERROR: [2] sizeof(): Parameter must be an array or an object that implements Countable

but not to worried about it since the end user doesn't see it.  I will continue testing and let you know if I find any more issues.

Thanks for all the help.

**Comment by jrosetto** [comment]
Spoke too soon.  When right clicking on an item under PORTAL > Events I got one more error.

e01390afee :: 2019-06-03 20:28:22 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderEmail.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderEmail::getAdvanceTime() should be compatible with TodoyuCalendarReminder::getAdvanceTime($type = CALENDAR_TYPE_EVENTREMINDER_EMAIL)
e01390afee :: 2019-06-03 20:28:22 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderEmail.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderEmail::isDisabled() should be compatible with TodoyuCalendarReminder::isDisabled($reminderType)
e01390afee :: 2019-06-03 20:28:22 - L:3 - U:jrosetto [core/model/TodoyuAutoloader.class.php:56] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderPopup::isDisabled() should be compatible with TodoyuCalendarReminder::isDisabled($reminderType)

**Comment by jrosetto** [comment]
> 
> 
> If this all works out, do you mind creating an Issue for a feature request. Something that you feel is missing from Todoyu for your company's workflow.
> 
> Thank you

Would be happy to.

**Comment by AlexEdimensionz** [comment]
BTW. I have a feeling that the sizeof() error you are getting at html:0 is in the smarty sheets somewhere
You may have to clear the template cache to make it go away

Delete all files in cache/ folder to be sure.

I did another push cleaning up the unchecked sizeof() calls

**Comment by AlexEdimensionz** [comment]
> Spoke too soon. When right clicking on an item under PORTAL > Events I got one more error.
> 
> e01390afee :: 2019-06-03 20:28:22 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderEmail.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderEmail::getAdvanceTime() should be compatible with TodoyuCalendarReminder::getAdvanceTime($type = CALENDAR_TYPE_EVENTREMINDER_EMAIL)
> e01390afee :: 2019-06-03 20:28:22 - L:3 - U:jrosetto [ext/calendar/model/TodoyuCalendarReminderEmail.class.php:27] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderEmail::isDisabled() should be compatible with TodoyuCalendarReminder::isDisabled($reminderType)
> e01390afee :: 2019-06-03 20:28:22 - L:3 - U:jrosetto [core/model/TodoyuAutoloader.class.php:56] :: PHP ERROR: [2] Declaration of TodoyuCalendarReminderPopup::isDisabled() should be compatible with TodoyuCalendarReminder::isDisabled($reminderType)

This is fixed in the latest push. 
Also remember to delete contents of ./cache/ folder

**Comment by jrosetto** [comment]
Everything looks good on my end now.

I did find one more error on login but everything works fine in the UI so I'm not worried about it, just thought I would mentune it.

0fd0880830 :: 2019-06-04 13:21:51 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable
0fd0880830 :: 2019-06-04 13:21:51 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable
0fd0880830 :: 2019-06-04 13:21:51 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable
0fd0880830 :: 2019-06-04 13:21:51 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable
0fd0880830 :: 2019-06-04 13:21:51 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable
0fd0880830 :: 2019-06-04 13:21:51 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable
0fd0880830 :: 2019-06-04 13:21:52 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable
0fd0880830 :: 2019-06-04 13:21:52 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable
0fd0880830 :: 2019-06-04 13:21:52 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable
0fd0880830 :: 2019-06-04 13:21:52 - L:3 - U: [lib/php/phpsass/tree/SassMixinNode                                                                                                                                                             .php:63] :: PHP ERROR: [2] count(): Parameter must be an array or an object that                                                                                                                                                              implements Countable

Thanks again for all the help.

I am going to sit down with a few other people to discuss what we need the most that is missing from TodoYU when I get a chance.

**Comment by AlexEdimensionz** [comment]
Thank you for that. I am aware of the issue with dependencies that haven't been updated since 2011, have been trying to find replacements or updates for them
